
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA EQ FROM GT ID INT LT SELECT STAR STRING WHEREquery : select_clause from_clause where_clause_optwhere_clause_opt : WHERE condition\n                        | emptyselect_clause : SELECT STAR\n                     | SELECT column_listcolumn_list : ID\n                   | column_list COMMA IDfrom_clause : FROM IDcondition : ID EQ INT\n                 | ID EQ STRING\n                 | ID GT INT\n                 | ID LT INTempty :'
    
_lr_action_items = {'SELECT':([0,],[3,]),'$end':([1,4,9,11,12,14,20,21,22,23,],[0,-13,-1,-3,-8,-2,-9,-10,-11,-12,]),'FROM':([2,6,7,8,16,],[5,-4,-5,-6,-7,]),'STAR':([3,],[6,]),'ID':([3,5,10,13,],[8,12,15,16,]),'WHERE':([4,12,],[10,-8,]),'COMMA':([7,8,16,],[13,-6,-7,]),'EQ':([15,],[17,]),'GT':([15,],[18,]),'LT':([15,],[19,]),'INT':([17,18,19,],[20,22,23,]),'STRING':([17,],[21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query':([0,],[1,]),'select_clause':([0,],[2,]),'from_clause':([2,],[4,]),'column_list':([3,],[7,]),'where_clause_opt':([4,],[9,]),'empty':([4,],[11,]),'condition':([10,],[14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('query -> select_clause from_clause where_clause_opt','query',3,'p_query','syntaxer.py',33),
  ('where_clause_opt -> WHERE condition','where_clause_opt',2,'p_where_clause_opt','syntaxer.py',46),
  ('where_clause_opt -> empty','where_clause_opt',1,'p_where_clause_opt','syntaxer.py',47),
  ('select_clause -> SELECT STAR','select_clause',2,'p_select_clause','syntaxer.py',58),
  ('select_clause -> SELECT column_list','select_clause',2,'p_select_clause','syntaxer.py',59),
  ('column_list -> ID','column_list',1,'p_column_list','syntaxer.py',71),
  ('column_list -> column_list COMMA ID','column_list',3,'p_column_list','syntaxer.py',72),
  ('from_clause -> FROM ID','from_clause',2,'p_from_clause','syntaxer.py',83),
  ('condition -> ID EQ INT','condition',3,'p_condition','syntaxer.py',90),
  ('condition -> ID EQ STRING','condition',3,'p_condition','syntaxer.py',91),
  ('condition -> ID GT INT','condition',3,'p_condition','syntaxer.py',92),
  ('condition -> ID LT INT','condition',3,'p_condition','syntaxer.py',93),
  ('empty -> <empty>','empty',0,'p_empty','syntaxer.py',104),
]
